# Generated by Django 6.0.6 on 2026-06-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('delivery_time', models.IntegerField()),
                ('address', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
