# Generated by Django 6.0.6 on 2026-06-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
