# Generated by Django 6.0.6 on 2026-06-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0015_fooditem_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
