# Generated by Django 6.0.6 on 2026-06-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0016_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(max_length=150),
        ),
    ]
