# Generated by Django 6.0.6 on 2026-06-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0017_alter_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
